config/routes.rb
Rails.application.routes.draw do
  
 scope "(:locale)", locale: /en|ja/ do
  get 'my_aj/new'
  get 'users_workspace/index'
  get 'users_workspace/update'
  root 'signup#index'
  get    '/signup',   to: 'signup#index'
  get    '/login',   to: 'session#new'
  post   '/login',   to: 'session#create'
  get 'logout', to: 'session#destroy'
  resources :signup
  get 'thread_replies/new'
  get 'thread_replies/show'
  get '/star', to:'messages#StarShow'
  get "/star",to:"messages#ssss"
  post "/star",to:"messages#star"

  get "/user", to:"signup#manage"

  


   resources :channels do
   	resources :channels_user
   end
resources :generals
resources :thread_replies
resources :messages
resources :user_management
resources :workspaces do 
  resources :users_workspace

end

end


end



 



  


 # get '/singup', to:'signup#new'
 # post '/signup', to:'signup#create'


 # get '/workspace/new', to:'workspace#new'
 # post '/workspace', to:'workspace#create'
#get  'workspace/show', to: 'workspace#show'
# get '/destroy/:id', to: 'workspace#delete'
# get '/edit/:id', to: 'workspace#edit'
# post '/workspace', to:'workspace#update'

# get '/dashboard', to:'dashboard#index'

# get '/edit', to:'dashboard#edit'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :workspace
  has_many :messages, dependent: :destroy
   has_many :channels_user, dependent: :destroy
   has_many :users, through: :channels_user
  validates :name,{presence:true,length:{maximum:255}}

  
end

app/models/channels_user.rb
class ChannelsUser < ApplicationRecord
  belongs_to :user
  belongs_to :channel
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :channel
  belongs_to :user
   has_many :thread_replies, dependent: :destroy
end

app/models/thread_reply.rb
class ThreadReply < ApplicationRecord
  belongs_to :message
  belongs_to :channel
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	  has_secure_password
	  has_many :users_workspace, dependent: :destroy
      has_many :workspaces, :through => :users_workspace
      has_many :messages
      has_many :channels_user,dependent: :destroy
      has_many :channels, :through => :channels_user
	  validates :name,{presence:true,length:{maximum:255}}
      validates :email,{presence:true,uniqueness:true,length:{maximum:255}}
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
     validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
     validates :password,{presence:true,length:{minimum:6}}
     validates :password_confirmation,{presence:true,length:{minimum:6}}      
end

app/models/users_workspace.rb
class UsersWorkspace < ApplicationRecord
  belongs_to :user
  belongs_to :workspace
end

app/models/workspace.rb
class Workspace < ApplicationRecord
	has_many :users_workspace, dependent: :destroy
has_many :users, :through => :users_workspace
has_many :channels, dependent: :destroy
	 validates :name,{presence:true,length:{maximum:255}}
end

app/controllers/channels_controller.rb
  class ChannelsController < ApplicationController


  def new
     @channel= Channel.new
     @workspace=Workspace.find_by_id(session[:current_workspace])
     @channels=Channel.where(:workspace_id => @workspace.id)
     @message = Message.new
     @cu = ChannelsUser.all
     @works = User.all.find_by(id: current_user).users_workspace
  end

  def index
    @cu = ChannelsUser.all
    @channels = Channel.all
    @channelsuser = User.all.find_by(id: current_user).channels_user
    @works = User.all.find_by(id: current_user).users_workspace
  end
  
  def create
    @channel = Channel.new(name:params[:name],workspace_id:params[:workspace_id],privacy:params[:privacy])
    @workspace= Workspace.find(params[:workspace_id])     
    if@channel.save
      @user_channel =ChannelsUser.new(:user => current_user, :channel => @channel, :role => "owner")
      @user_channel.save
      @workspace= Workspace.find(params[:workspace_id])
      session[:channels_list]=@channel.id
      flash[:notice] = t(:"Channel Successfully create")
      redirect_to workspace_path(@workspace)
    else
      render "new"
    end
  end

  def edit
    @channel = Channel.find(params[:id])
    @cu = ChannelsUser.all
    @workspace=Workspace.find_by_id(session[:current_workspace])
    @channels=Channel.where(:workspace_id => @workspace.id)
    @usersworkspace=UsersWorkspace.all
    @channelsuser=User.all.find_by(id: current_user).channels_user
    @works = User.all.find_by(id: current_user).users_workspace   
  end

  def update
    @channel = Channel.find(params[:id])
    @cu = ChannelsUser.all
    @works = User.all.find_by(id: current_user).users_workspace
    if @channel.update(channel_params)
      @workspace=Workspace.find(session[:current_workspace])
      flash[:notice] = t(:"Channel edit successful")
      redirect_to workspace_path(@workspace)
    else
      flash[:alert] = t(:"Channel edit fail")
      render "edit"
    end
  end

  def show
   @works = User.all.find_by(id: current_user).users_workspace
   @channel= Channel.find(params[:id])
   @usersworkspace=UsersWorkspace.all
   @message=Message.new
   @thread=ThreadReply.new
   @cu = ChannelsUser.all
   @threadList=ThreadReply.all
   @messages=Message.all.includes(:user).where(channel_id: @channel)
   @workspace=Workspace.find_by_id(session[:current_workspace])
   @channels=Channel.where(:workspace_id => @workspace.id)   
   @usersworkspace=User.all.find_by(id: current_user).users_workspace
   @channelsuser=User.all.find_by(id: current_user).channels_user
  end

  def destroy
   @works = User.all.find_by(id: current_user).users_workspace
   Channel.find(params[:id]).destroy
   @cu = ChannelsUser.all
   @workspace=Workspace.find(session[:current_workspace])
   redirect_to workspace_path(@workspace)   
  end

  def check_for_cancel
   if params[:commit] == "Cancel"
    redirect_to channel_path
   end
  end

private

def channel_params
  params.require(:channel).permit(:name,:workspace_id,:privacy)
end

end

app/controllers/home_controller.rb
	class HomeController < ApplicationController
	  def index
	  end
	end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_workspace
  
  end
end

app/helpers/channel_helper.rb
module ChannelHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
   def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
end

def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
        concat form.label(field, class: 'control-label') if label
        concat capture(&block)
        concat errors_for(form, field)
    end
end	 
end

app/helpers/generals_helper.rb
module GeneralsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/my_aj_helper.rb
module MyAjHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/session_helper.rb
module SessionHelper
# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/signup_helper.rb
module SignupHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
end

def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
        concat form.label(field, class: 'control-label') if label
        concat capture(&block)
        concat errors_for(form, field)
    end
end
end

app/helpers/workspace_helper.rb
module WorkspaceHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
	def errors_for(form, field)
        content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
    end

    def form_group_for(form, field, opts={}, &block)
        label = opts.fetch(:label) { true }
        has_errors = form.object.errors[field].present?

        content_tag :div, class: "form-group #{'has-error' if has_errors}" do
            concat form.label(field, class: 'control-label') if label
            concat capture(&block)
            concat errors_for(form, field)
        end
    end
end

app/views/channels/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info justify-content-between">
  <a class="navbar-brand text-white font-weight-bold" href="#"><%= t("channels._navbar.Team3 chat Application") %></a>
  <div class="dropdown show">
   <%= link_to "<i class='fa fa-star stars'></i>".html_safe, star_path,style:"margin-right: 10px;" %>
    <div class="btn" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="glyphicon glyphicon-envelope"><i class="fa fa-cog"></i></span></div>
      <div class="dropdown-menu text-info" aria-labelledby="dropdownMenuLink">
        <% if  @channelsuser %>
            <%  @channelsuser.each do|channelsuser| %>
                <% if channelsuser.role=='owner' && channelsuser.channel_id==@channel.id %>
        <p style="margin-left: 29px"><%= link_to t('channels._navbar.Edit'), edit_channel_path(@channel), method: 'get',class:'text-info font-weight-bold' %></a></p>
        <p style="margin-left: 29px"> <%= link_to t('channels._navbar.Remove'),channel_path(@channel), method: 'delete', data: { confirm: 'Are you sure?' },class:'text-info font-weight-bold' %></a></p>
         <% else %> 
          <% end %>
          <% end %>
          <% else %>
          <% end %>
        <p style="margin-left: 29px"><%= link_to t('channels._navbar.Invite'), channel_channels_user_index_path(@channel),class:'text-info font-weight-bold' %></p>      
      </div>
    <% if current_user %>
   <b style="color: white" ><%= current_user.name %>  |</b>  
    <%= link_to t('layouts._navbar.Logout'), logout_path, style:"color:white;" %> <b style="color:white"> | </b>
    <% else %> 
    <%= link_to t('layouts._navbar.Sign In'), login_path %> <%= link_to t('layouts._navbar.Sign Up'), new_signup_path %>
    <% end %>  
    
    <% if I18n.locale == I18n.default_locale %>
     <%= link_to t('layouts._navbar.Japan'),{:locale => 'ja'}, style:"color:white;margin-right:110px;" %> 
     <% else %>
     <%= link_to t('layouts._navbar.English'),{:locale => 'en'}, style:"color:white;" %> 
     <% end %>

     </div>
</nav>

app/views/channels/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render 'navbar' %>
  <div class="sidenav">
    <%= render 'layouts/sidebar' %>
  </div>
  <div class="container" style="margin-top: 80px;">
    <div class="row">
      <div class="col-sm-6 offset-3">
       <div class="card">
        <h5 class="card-header info-color white-text text-center text-info">
          <strong><%= t('channels.edit.Edit Channel') %></strong>
        </h5>
        <div class="card-body text-danger">
         <%= form_with model: @channel do |form| %>
         <div class="form-group text-info text-uppercase">
          <%= form.label :name %>
         
              <% if @channel.errors.any? %>
             <div id="error_explanation">
             <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this article from being saved:</h2>
 
              <ul>
              <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
             <% end %>
              </ul>
              </div>
             <% end %>
          <%= form.text_field :name, placeholder: t('channels.edit.Edit Channel Name'),class:'form-control' %>
        </div>
        <center> <div class="form-group">
         <%= form.submit class: "btn btn-info" %>
         <%= link_to t('channels.edit.Cancel'), channel_path(@channel), class: "btn btn-info" %>  
       </div></center>
       <% end %>
     </div>
     <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' 
        });
      });
    </script>
  </div>
</body>
</html> 

app/views/channels/index.html.erb
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chap Application</title>
  <div class="wrapper hold-transition skin-blue layout-top-nav">
    <header class="main-header  ">
      <nav class="navbar navbar-static-top">
        <div class="container">
          <div class="navbar-header">
            <a href="" class="navbar-brand"><b>Chat Apbp</b></a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
              <i class="fa fa-bars"></i>
            </button>
          </div>        
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
             <ul class="nav navbar-nav">
              <li class="dropdown">
                <li>
                </li>
              </li>
            </ul>           
          </ul>
        </div>       
      </div>      
    </nav>
  </header>
  <body>
    <table>
      <% @channels.each do |channel| %>
      <% tmp = 0 %>
      <% @cu.each do |cu|%>
      <% if cu.user_id == current_user.id and cu.channel_id == channel.id %>
      <% tmp = 1%>
      <% end %>
      <% end %>
      <% if channel.privacy == true %>
      <li class="list-group-item">#<%= link_to channel.name, channel_path(channel) %></li>
      <% else %>
      <% if tmp == 1 %>
      <li class="list-group-item">#<%= link_to channel.name, channel_path(channel) %></li>
      <% else %>
      <% end %>
      <% end %>
      <% end %>
    </table>
  </body>
</div>
</html>

app/views/channels/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="sidenav">
    <%= render 'layouts/sidebar' %>
  </div>
  <div class="container" style="margin-top: 80px;">
    <div class="row">
      <div class="col-sm-6 offset-3">
       <div class="card">

        <h5 class="card-header info-color white-text text-center text-info">
          <strong><%= t('channels.new.Add New Channel') %></strong>
        </h5>
        

        <div class="card-body text-danger">
          <%= form_for(@channel) do |f| %> 
            <%= f.label :name,class: 'text-info text-uppercase' %>
            <%= form_group_for f, :name, label: false  do %>
            <div class="Input-group"> 
            <%= f.text_field :name, class: 'form-control' ,name:"name",placeholder: t('channels.new.Enter Channel Name') %>
            </div> <% end %>
          <div>
           <%= f.hidden_field :workspace_id, value: @workspace.id ,name:"workspace_id" %>
         </div>
         <div class="form-group text-info text-uppercase">
          <%= f.check_box :privacy, name:'privacy' %>
          <%= f.label :Public %>
        </div>
        <div class="col-xs-3">
         <center> <div class="form-group">
           <%= f.submit t('channels.new.Save'), class: "btn btn-info" %>
           <%= link_to t('channels.new.Cancel'), workspace_path(@workspace), class: "btn btn-info" %>
         </div></center>
       </div>
       <% end %>   
     </div>
     <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' 
        });
      });
    </script>
  </div>

</body>
</html> 

app/views/channels/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render 'channels/navbar' %>
  <div class="sidenav">
    <%= render 'layouts/sidebar' %>
  </div>
  <div style="overflow:hidden;width:100%">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 offset-3">
          <table class="table table-hover">
          </table>
          <div class="form-group mx-sm-0">
          </div>
        </div>
      </div>
      <div id="message_container">
        <div style="margin-left: 300px; height: 400px;overflow-y: scroll; margin-top: -30px;" >
         <% if @messages %>
         <% @messages.each do |message| %>
         <%=  message.user.email %> | <%= message.created_at %>
         <div class="alert alert-primary" role="alert"> 
          <%=  message.name %>
          <% if message.favourite == true %>
          <i onclick="gofavourite(this)" star_id="<%= message.id %>" class="fa fa-star stars" style="position: absolute;left:90%;z-index: 999;color:yellow;"></i>
          <% else %>
          <i onclick="gofavourite(this)" star_id="<%= message.id %>" class="fa fa-star stars" style="position: absolute;left:90%;z-index: 999;"></i>
          <% end %>  
          <br>
          <a><%= link_to t('channels.show.Remove'), message_path(message), method: 'delete', data: { confirm: 'Are you sure?' } %></a> .
          <%= link_to t('channels.show.Edit'), edit_message_path(message), method: 'get'%>
          <%= form_tag("/star", method: "post",id:"form2" ,style:"transform:translate(0,-100%);") do %>
          <input type="hidden" name="star_id" id="star_hidden" >
          <% end %>
          <div class="float-right">
            <%= form_for @thread, :url => url_for(:controller => 'thread_replies', :action => 'create') do |f| %>
            <%= f.hidden_field :channel_id, value: @channel.id ,name:"channel_id" %>
            <%= f.hidden_field :message_id, value: message.id ,name:"message_id" %>
            <a data-toggle="collapse" href="#" data-target="#collapse-<%= message.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
             <%= t('channels.show.Reply') %>  
           </a>
           |
           <a data-toggle="collapse" href="#" data-target="#collapse1-<%= message.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
             <%= t('channels.show.View') %>
           </a> 
         </div>
         <br>
         <div class="collapse" id="collapse-<%= message.id %>"> 
          <div class="form-group"> 
            <%= f.text_area :text, name:'text', class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.submit t('channels.show.Send'), class: 'btn btn-primary btn-sm' %>
          </div>
        </div>
        <div class="collapse" id="collapse1-<%= message.id %>">       
          <div class="form-group">
           <ul class="list-group"> 
            <% @threadList.each do |thread| %>     
            <% if thread.message_id == message.id %>
            <%= message.user.email %> | <%= thread.created_at %><br>
            <li class="list-group-item list-group-item-info">        
             <%= thread.text %>
             <i class="float-lg-right">
               <%= link_to t('channels.show.Remove'), thread_reply_path(thread), method:'delete', data:{confirm:'Are you sure?'} %>
             </i>
           </li>
         </ul>
         <% end %>
         <% end %>
       </div>
     </div>
     <% end %>
   </div>   
   <% end %>
   <% else %>
   <div class="alert alert-primary" role="alert"> Lets Chat!"</div>
   <% end %>
 </div>
</div>
<!--  -->
<div class="textMessage">
  <%= form_for @message, :url => url_for(:controller => 'messages', :action => 'create') do |f| %>
  <%= f.hidden_field :channel_id, value: @channel.id ,name:"channel_id" %>
  <div class="text-container">   
  </div>
  <div class="form-group">
    <%= f.text_area :name, name:'name', class: 'form-control' %>
  </div>
  <div class="form-group">
   <%= f.submit t('channels.show.Send'), class: 'btn btn-primary btn-sm' %>
 </div>
 <% end %>
</div>
</div>
</div>
</body>
<script>
  function gofavourite(a){
    var demo = a.getAttribute("star_id");
    document.getElementById("star_hidden").value = demo;
    document.getElementById("form2").submit();
  }
</script>
</html> 