config/routes.rb
Rails.application.routes.draw do
  
 scope "(:locale)", locale: /en|ja/ do
  get 'my_aj/new'
  get 'users_workspace/index'
  get 'users_workspace/update'
  root 'signup#index'
  get    '/signup',   to: 'signup#index'
  get    '/login',   to: 'session#new'
  post   '/login',   to: 'session#create'
  get 'logout', to: 'session#destroy'
  resources :signup
  get 'thread_replies/new'
  get 'thread_replies/show'
  get '/star', to:'messages#StarShow'
  get "/star",to:"messages#ssss"
  post "/star",to:"messages#star"

  get "/user", to:"signup#manage"

  


   resources :channels do
   	resources :channels_user
   end
resources :generals
resources :thread_replies
resources :messages
resources :user_management
resources :workspaces do 
  resources :users_workspace

end

end


end



 



  


 # get '/singup', to:'signup#new'
 # post '/signup', to:'signup#create'


 # get '/workspace/new', to:'workspace#new'
 # post '/workspace', to:'workspace#create'
#get  'workspace/show', to: 'workspace#show'
# get '/destroy/:id', to: 'workspace#delete'
# get '/edit/:id', to: 'workspace#edit'
# post '/workspace', to:'workspace#update'

# get '/dashboard', to:'dashboard#index'

# get '/edit', to:'dashboard#edit'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :workspace
  has_many :messages, dependent: :destroy
   has_many :channels_user, dependent: :destroy
   has_many :users, through: :channels_user
  validates :name,{presence:true,length:{maximum:255}}

  
end

app/models/channels_user.rb
class ChannelsUser < ApplicationRecord
  belongs_to :user
  belongs_to :channel
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :channel
  belongs_to :user
   has_many :thread_replies, dependent: :destroy
end

app/models/thread_reply.rb
class ThreadReply < ApplicationRecord
  belongs_to :message
  belongs_to :channel
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	  has_secure_password
	  has_many :users_workspace, dependent: :destroy
      has_many :workspaces, :through => :users_workspace
      has_many :messages
      has_many :channels_user,dependent: :destroy
      has_many :channels, :through => :channels_user
	  validates :name,{presence:true,length:{maximum:255}}
      validates :email,{presence:true,uniqueness:true,length:{maximum:255}}
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
     validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
     validates :password,{presence:true,length:{minimum:6}}
     validates :password_confirmation,{presence:true,length:{minimum:6}}      
end

app/models/users_workspace.rb
class UsersWorkspace < ApplicationRecord
  belongs_to :user
  belongs_to :workspace
end

app/models/workspace.rb
class Workspace < ApplicationRecord
	has_many :users_workspace, dependent: :destroy
has_many :users, :through => :users_workspace
has_many :channels, dependent: :destroy
	 validates :name,{presence:true,length:{maximum:255}}
end

app/controllers/users_workspace_controller.rb
    class UsersWorkspaceController < ApplicationController

     def index  
       @users = User.where.not(id: current_user)
       @workspace=Workspace.find_by_id(session[:current_workspace])
       @channels=Channel.where(:workspace_id => @workspace.id)
       @usersworkspace=UsersWorkspace.all
       @works = User.all.find_by(id: current_user).users_workspace
       @cu = ChannelsUser.all
       @channelsuser=User.all.find_by(id: current_user).channels_user
     end

     def update  
       @invite_user = User.find(params[:id])
       @invite_workspace = Workspace.find(params[:workspace_id])
       @is_invite =UsersWorkspace.find_by(user: @invite_user, workspace:@invite_workspace, role: "member")
       @is_uninvite = UsersWorkspace.find_by(user: @invite_user, workspace:@invite_workspace, role: "")
       if @is_invite.nil? && @is_uninvite.nil?
        @curr_invite = UsersWorkspace.new(:user => @invite_user, :workspace =>@invite_workspace, :role => "member")
        if @curr_invite.save
          redirect_to :action => 'index'
        end
     end

     if !@is_invite.nil?
        @is_invite.update_attribute(:role, "")
        redirect_to :action => 'index'
     end

     if !@is_uninvite.nil?
        @is_uninvite.update_attribute(:role, "member")
        redirect_to :action => 'index'
     end
    end
  end

app/helpers/channel_helper.rb
module ChannelHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
   def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
end

def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
        concat form.label(field, class: 'control-label') if label
        concat capture(&block)
        concat errors_for(form, field)
    end
end	 
end

app/helpers/generals_helper.rb
module GeneralsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/my_aj_helper.rb
module MyAjHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/session_helper.rb
module SessionHelper
# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/signup_helper.rb
module SignupHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
end

def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
        concat form.label(field, class: 'control-label') if label
        concat capture(&block)
        concat errors_for(form, field)
    end
end
end

app/helpers/users_workspace_helper.rb
module UsersWorkspaceHelper
end

app/helpers/workspace_helper.rb
module WorkspaceHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
	def errors_for(form, field)
        content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
    end

    def form_group_for(form, field, opts={}, &block)
        label = opts.fetch(:label) { true }
        has_errors = form.object.errors[field].present?

        content_tag :div, class: "form-group #{'has-error' if has_errors}" do
            concat form.label(field, class: 'control-label') if label
            concat capture(&block)
            concat errors_for(form, field)
        end
    end
end

app/views/users_workspace/index.html.erb
  <!DOCTYPE html>
  <html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="sidenav">  
     <%= render 'layouts/sidebar' %>
   </div>
   <div class="row" style="margin-top:50px;margin-left: 200px;">
    <div class="col-sm-6 offset-sm-3">
     <table class="table table-dark">
      <thead>
        <tr>  
          <th scope="col"><%= t("users_workspace.index.Name") %></th>
          <th scope="col"><%= t("users_workspace.index.Email") %></th>
          <th scope="col"><%= t("users_workspace.index.Invite User") %></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <% if !user.users_workspace.find_by(workspace_id: params[:workspace_id]).nil? %>
            <% if user.users_workspace.find_by(workspace_id: params[:workspace_id]).role == 'member' %>
            <%= link_to t('users_workspace.index.Uninvite'),workspace_users_workspace_path(params[:workspace_id], user), method: :put, class: "btn btn-primary btn-sm", id: user.id %>
            <% end %>
            <% if user.users_workspace.find_by(workspace_id: params[:workspace_id]).role.empty? %>
            <%= link_to t('users_workspace.index.Invite'), workspace_users_workspace_path(params[:workspace_id], user), method: :put, class: "btn btn-primary btn-sm", id: user.id %>
            <% end %>
            <% end %>
            <% if user.users_workspace.find_by(workspace_id: params[:workspace_id]).nil? %>
            <%= link_to t('users_workspace.index.Invite'), workspace_users_workspace_path(params[:workspace_id], user), method: :put, class: "btn btn-primary btn-sm", id: user.id %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>
</body>
</html> 