config/routes.rb
Rails.application.routes.draw do
  
 scope "(:locale)", locale: /en|ja/ do
  get 'my_aj/new'
  get 'users_workspace/index'
  get 'users_workspace/update'
  root 'signup#index'
  get    '/signup',   to: 'signup#index'
  get    '/login',   to: 'session#new'
  post   '/login',   to: 'session#create'
  get 'logout', to: 'session#destroy'
  resources :signup
  get 'thread_replies/new'
  get 'thread_replies/show'
  get '/star', to:'messages#StarShow'
  get "/star",to:"messages#ssss"
  post "/star",to:"messages#star"

  get "/user", to:"signup#manage"

  


   resources :channels do
   	resources :channels_user
   end
resources :generals
resources :thread_replies
resources :messages
resources :user_management
resources :workspaces do 
  resources :users_workspace

end

end


end



 



  


 # get '/singup', to:'signup#new'
 # post '/signup', to:'signup#create'


 # get '/workspace/new', to:'workspace#new'
 # post '/workspace', to:'workspace#create'
#get  'workspace/show', to: 'workspace#show'
# get '/destroy/:id', to: 'workspace#delete'
# get '/edit/:id', to: 'workspace#edit'
# post '/workspace', to:'workspace#update'

# get '/dashboard', to:'dashboard#index'

# get '/edit', to:'dashboard#edit'

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :workspace
  has_many :messages, dependent: :destroy
   has_many :channels_user, dependent: :destroy
   has_many :users, through: :channels_user
  validates :name,{presence:true,length:{maximum:255}}

  
end

app/models/channels_user.rb
class ChannelsUser < ApplicationRecord
  belongs_to :user
  belongs_to :channel
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :channel
  belongs_to :user
   has_many :thread_replies, dependent: :destroy
end

app/models/thread_reply.rb
class ThreadReply < ApplicationRecord
  belongs_to :message
  belongs_to :channel
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	  has_secure_password
	  has_many :users_workspace, dependent: :destroy
      has_many :workspaces, :through => :users_workspace
      has_many :messages
      has_many :channels_user,dependent: :destroy
      has_many :channels, :through => :channels_user
	  validates :name,{presence:true,length:{maximum:255}}
      validates :email,{presence:true,uniqueness:true,length:{maximum:255}}
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
     validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
     validates :password,{presence:true,length:{minimum:6}}
     validates :password_confirmation,{presence:true,length:{minimum:6}}      
end

app/models/users_workspace.rb
class UsersWorkspace < ApplicationRecord
  belongs_to :user
  belongs_to :workspace
end

app/models/workspace.rb
class Workspace < ApplicationRecord
	has_many :users_workspace, dependent: :destroy
has_many :users, :through => :users_workspace
has_many :channels, dependent: :destroy
	 validates :name,{presence:true,length:{maximum:255}}
end

app/helpers/channel_helper.rb
module ChannelHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
   def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
end

def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
        concat form.label(field, class: 'control-label') if label
        concat capture(&block)
        concat errors_for(form, field)
    end
end	 
end

app/helpers/generals_helper.rb
module GeneralsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/my_aj_helper.rb
module MyAjHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/session_helper.rb
module SessionHelper
# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/signup_helper.rb
module SignupHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
end

def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
        concat form.label(field, class: 'control-label') if label
        concat capture(&block)
        concat errors_for(form, field)
    end
end
end

app/helpers/workspace_helper.rb
module WorkspaceHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
	def errors_for(form, field)
        content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
    end

    def form_group_for(form, field, opts={}, &block)
        label = opts.fetch(:label) { true }
        has_errors = form.object.errors[field].present?

        content_tag :div, class: "form-group #{'has-error' if has_errors}" do
            concat form.label(field, class: 'control-label') if label
            concat capture(&block)
            concat errors_for(form, field)
        end
    end
end

app/views/layouts/_admin_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <a class="navbar-brand" href="#">Rails chat Application</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_user %>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       
        <%= current_user.name %>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
         <%= link_to "Log out", logout_path, method: :delete %>
      </div>
    </div>
  <% end %>
</nav>

app/views/layouts/_footer.html.erb
<footer class="main-footer" style="margin-top: 640px">
    <div class="pull hidden-xs text-center">
      <strong>Team3 Chat Application</strong>
    </div>  
</footer>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <link rel="stylesheet" href="">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-info justify-content-between">
    <a class="navbar-brand text-white font-weight-bold" href="#"><%= t('layouts._navbar.Team3ChatApplication') %></a>
    <div class="navbar-light text-white">
     <% if current_user %>
     <%= current_user.name %> |
     <%= link_to t('layouts._navbar.Logout'), logout_path, style:"color:white;" %> |
     <% else %> 
     <%= link_to t('layouts._navbar.Sign In'), login_path, style:"color:white;" %> |
     <%= link_to t('layouts._navbar.Sign Up'), signup_path, style:"color:white;" %> |
     <% end %>  

     <% if I18n.locale == I18n.default_locale %>
     <%= link_to t('layouts._navbar.Japan'),{:locale => 'ja'}, style:"color:white;" %> 
     <% else %>
     <%= link_to t('layouts._navbar.English'),{:locale => 'en'}, style:"color:white;" %> 
     <% end %>
   </div>
 </nav>
</body>
</html>

app/views/layouts/_sidebar.html.erb
    <ul class="list-group">
      <li class="list-group-item">
        <div class="dropdown">
          <button class="btn dropdown-toggle text-info font-weight-bold" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <%= @workspace.name %>
         </button>
         <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% if @works %>
          <% @works.each do|usersworkspace| %>
          <% if usersworkspace.role=='owner' && usersworkspace.workspace_id==@workspace.id %>
          <p style="margin-left: 29px"><%= link_to t('workspaces._form.Edit'), edit_workspace_path(@workspace), method: 'get', class:'text-info' %></p>
          <p style="margin-left: 29px"> <a class="dropdown-item" href="#"><%= link_to t('workspaces._form.Remove'), workspace_path(@workspace), method: 'delete', data: { confirm: 'Are you sure?' }, class:'text-info' %></a></p>
          <p style="margin-left: 5px"> <a class="dropdown-item" href="#"><%= link_to t('layouts._sidebar.Switch To New Workspce'), workspaces_path, class:'text-info' %></a></p>
          <!-- <a class="dropdown-item" href="#"></a> -->     
          <% else %> 
          <% end %>
          <% end %>
          <% else %>
          <% end %>
        </div>
      </div></li>
      <li class="list-group-item d-flex justify-content-between align-items-center text-info font-weight-bold">
        <%= t('workspaces._form.Add New Channel') %>
        <span class="badge  badge-pill">
         <%= link_to " #", new_channel_path(:id =>@workspace.id) %></span>
       </li>
       <% if @channels %>
       <% @channels.each do |channel| %>
       <% tmp = 0 %>
       <% @cu.each do |cu|%>
       <% if cu.user_id == current_user.id and cu.channel_id == channel.id %>
       <% tmp = 1%>
       <% end %>
       <% end %>
       <% if channel.privacy == true %>
       <li class="list-group-item">#<%= link_to channel.name, channel_path(channel), class:'font-weight-bold text-info' %></li>
       <% else %>
       <% if tmp == 1 %>
       <li class="list-group-item">#<%= link_to channel.name, channel_path(channel), class:'font-weight-bold text-info' %></li>
       <% else %>
       <% end %>
       <% end %>    
       <% end %>
       <% else %>
       <% end %>
     </ul>
     <li class="list-group-item"><%= link_to t("layouts._sidebar.Invite"), workspace_users_workspace_index_path(@workspace), class:'font-weight-bold text-info' %></li> 
    
   
       

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
  </head>

  <body>
      
        <%= yield %>
            
         
         <% if alert %>
        <p class ="alert alert-danger"><%= alert %> </p>
        <% end %>

        <% if notice %>
        <div class="col-sm-6 offset-sm-3"> <p class ="alert alert-success"><%= notice %> </p></div>
        <% end %>
  
  </body>
</html>